name: sales_navigator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  mysql1: ^0.20.0
  flutter_widget_from_html: ^0.14.11
  shared_preferences: ^2.2.3
  path: ^1.9.0
  sqflite: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  
  assets:
    - photo/
