name: sales_navigator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.19.0
  sqflite: ^2.0.0
  shared_preferences: ^2.0.7
  google_nav_bar: ^5.0.6
  intl: ^0.19.0
  dropdown_button2: ^2.3.9
  email_validator: ^2.1.17
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - asset/logo/
  - asset/photo/
  - asset/
