name: sales_navigator
description: "Sales Navigator - Customer Relationship Management (CRM) Sales Management"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.36.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.0
  mysql1: ^0.20.0
  intl: ^0.17.0
  shared_preferences: any
  google_nav_bar: any
  crypto: any
  flutter_widget_from_html: ^0.14.11
  google_fonts: ^6.2.0
  timezone: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - photo/
    - asset/logo/
    - asset/
    - asset/photo/
